{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.ruintazila",
    "module": "dm-plugin",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dm-plugin-0.1.8.jar",
          "url": "dm-plugin-0.1.8.jar",
          "size": 30150,
          "sha512": "5886a625e825f50df494162bd7237d1b654182b0fcc4520f0f3892186a9e02cd98ee9b0c08c6097bcab40ac428710417c3d81342abe732268c8e7888872f8d80",
          "sha256": "e66bbb965ee90fb58d7ab22edefd2b536b781c33570e49e3121d1b89c397446d",
          "sha1": "83655700fcd941b759e700b5a6882e2efdcee369",
          "md5": "dbae703bc3d0047dfed9f8de461a8a6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "dm-plugin-0.1.8.jar",
          "url": "dm-plugin-0.1.8.jar",
          "size": 30150,
          "sha512": "5886a625e825f50df494162bd7237d1b654182b0fcc4520f0f3892186a9e02cd98ee9b0c08c6097bcab40ac428710417c3d81342abe732268c8e7888872f8d80",
          "sha256": "e66bbb965ee90fb58d7ab22edefd2b536b781c33570e49e3121d1b89c397446d",
          "sha1": "83655700fcd941b759e700b5a6882e2efdcee369",
          "md5": "dbae703bc3d0047dfed9f8de461a8a6a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dm-plugin-0.1.8-javadoc.jar",
          "url": "dm-plugin-0.1.8-javadoc.jar",
          "size": 261,
          "sha512": "15e3ac946f78c680973897a9ada018fd33b695f00e58fd144d9dced6a290f463b38f4f987e836c7b129210f4b5b57589adc81f7d331186664b464e1fbcf99f07",
          "sha256": "7f1e62cfa47517a7d4debafc4651419e6ebdfc1a3fbff0fd4ddf23c4bb07cc34",
          "sha1": "beed5e29716cee1bbe7046a1e067cb8ff43805bf",
          "md5": "2a63eeb80f7d57fd76f10f4e88f21c9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dm-plugin-0.1.8-sources.jar",
          "url": "dm-plugin-0.1.8-sources.jar",
          "size": 2345,
          "sha512": "56521d23a115efcc3ee312bb363dcc509197f1fc0a904afab19b7ffe2594d0be75e65def67daf0cdae2aa9dc2f919f4b76473bfcee5052dc9a7fd727c47d4890",
          "sha256": "348b0725e2dcfdd709b78b16ec586169dcff79d9c6e95c20da177bb848b3e647",
          "sha1": "8b65f58f66ccd2bc25fa87ca73ee160ecd62810f",
          "md5": "706f5ca1526f3f7624fd95ef8627eb64"
        }
      ]
    }
  ]
}
