[versions]
# build config
compileSdk = "33"
java-major = "11"
java = "11"
dm-plugin = "0.1.4"
# kotlin
kotlin = "1.7.20"
kotlin-ksp = "1.7.10-1.0.6"
kotlin-serialization = "1.4.0"
kotlin-coroutines = "1.6.4"
ktor = "2.1.1"

# plugin
android = "7.3.1"
spotless = "6.12.0"
ktlint = "0.47.1"
dependencies-update = "0.44.0"
version-catalog-update = "0.7.0"
gradle-publish = "1.1.0"
# androidx
androidx-appcompat = "1.5.1"
ktx-core = "1.9.0"
# compose
compose = "1.3.1"
compose-compiler = "1.3.2"
compose-meterial = "1.0.0-beta02"
compose-paging = "1.0.0-alpha16"
compose-navigation = "1.0.2"
material = "1.7.0"
# other official library
# test
junit = "4.13.2"
androidx-test = "1.4.0"
androidx-test-ext = "1.1.4"
androidx-test-espresso = "3.5.0"
# third party
mmkv = "1.2.14"
retrofit = "2.9.0"
okhttp = "4.10.0"
glide = "4.14.2"
rxpermission = "0.11"
leakcanary = "2.10"
koom = "2.2.1"

[libraries]
# androidx
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx-core" }
androidx-material = { module = "com.google.android.materia:materiall", version.ref = "material" }
# ui
# kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-script-runtime = { module = "org.jetbrains.kotlin:kotlin-script-runtime", version.ref = "kotlin" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
# plugin dependencies
plugin-gradle-android = { module = "com.android.tools.build:gradle", version.ref = "android" }
plugin-gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
# compose
# hilt
# test
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
# third party
mmkv = { module = "com.tencent:mmkv-static", version.ref = "mmkv" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-adapter-rxjava = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
#okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
#okhttp3-interceptor-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
rxpermission = { module = "com.github.tbruyelle:rxpermissions", version.ref = "rxpermission" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
java-library = { id = "org.gradle.java-library" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#kotlin-dsl = { id = "org.gradle.kotlin.kotlin-dsl", version.ref = "kotlin-dsl" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dependencies-update = { id = "com.github.ben-manes.versions", version = "dependencies-update" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version = "version-catalog-update" }

ktlint = { id = "com.pinterest:ktlint", version.ref = "ktlint" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }

[bundles]

